config/routes.rb
Rails.application.routes.draw do
  resources :move_sets
  resources :battle_logs
  resources :player_heros
  resources :heros
  devise_for :players
  devise_scope :player do
    root to: "devise/sessions#new"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hero.rb
class Hero < ApplicationRecord
end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  before_action :set_hero, only: [:show, :edit, :update, :destroy]

  # GET /heros
  # GET /heros.json
  def index
    @heros = Hero.all
  end

  # GET /heros/1
  # GET /heros/1.json
  def show
  end

  # GET /heros/new
  def new
    @hero = Hero.new
  end

  # GET /heros/1/edit
  def edit
  end

  # POST /heros
  # POST /heros.json
  def create
    @hero = Hero.new(hero_params)

    respond_to do |format|
      if @hero.save
        format.html { redirect_to @hero, notice: 'Hero was successfully created.' }
        format.json { render :show, status: :created, location: @hero }
      else
        format.html { render :new }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heros/1
  # PATCH/PUT /heros/1.json
  def update
    respond_to do |format|
      if @hero.update(hero_params)
        format.html { redirect_to @hero, notice: 'Hero was successfully updated.' }
        format.json { render :show, status: :ok, location: @hero }
      else
        format.html { render :edit }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heros/1
  # DELETE /heros/1.json
  def destroy
    @hero.destroy
    respond_to do |format|
      format.html { redirect_to heros_url, notice: 'Hero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hero
      @hero = Hero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hero_params
      params.require(:hero).permit(:name, :max_fire, :max_earth, :max_water, :max_wind, :max_atk, :max_lif, :max_def, :portarit_pic, :front_image, :back_image)
    end
end

app/helpers/heros_helper.rb
module HerosHelper
end

app/views/heros/_form.html.slim
= form_with(model: hero, local: true) do |form|
  - if hero.errors.any?
    #error_explanation
      h2
        = pluralize(hero.errors.count, "error")
        | prohibited this hero from being saved:
      ul
        - hero.errors.full_messages.each do |message|
          li= message
  .field
    = form.label :name
    = form.text_field :name, id: :hero_name
  .field
    = form.label :max_fire
    = form.number_field :max_fire, id: :hero_max_fire
  .field
    = form.label :max_earth
    = form.number_field :max_earth, id: :hero_max_earth
  .field
    = form.label :max_water
    = form.text_field :max_water, id: :hero_max_water
  .field
    = form.label :max_wind
    = form.number_field :max_wind, id: :hero_max_wind
  .field
    = form.label :max_atk
    = form.number_field :max_atk, id: :hero_max_atk
  .field
    = form.label :max_lif
    = form.number_field :max_lif, id: :hero_max_lif
  .field
    = form.label :max_def
    = form.number_field :max_def, id: :hero_max_def
  .field
    = form.label :portarit_pic
    = form.text_field :portarit_pic, id: :hero_portarit_pic
  .field
    = form.label :front_image
    = form.text_field :front_image, id: :hero_front_image
  .field
    = form.label :back_image
    = form.text_field :back_image, id: :hero_back_image
  .actions
    = form.submit

app/views/heros/edit.html.slim
h1 Editing Hero
= render 'form', hero: @hero
= link_to 'Show', @hero
| \
= link_to 'Back', heros_path

app/views/heros/index.html.slim
p#notice= notice
h1 Heros
table
  thead
    tr
      th Name
      th Max fire
      th Max earth
      th Max water
      th Max wind
      th Max atk
      th Max lif
      th Max def
      th Portarit pic
      th Front image
      th Back image
      th colspan: "3" 
  tbody
    - @heros.each do |hero|
      tr
        td= hero.name
        td= hero.max_fire
        td= hero.max_earth
        td= hero.max_water
        td= hero.max_wind
        td= hero.max_atk
        td= hero.max_lif
        td= hero.max_def
        td= hero.portarit_pic
        td= hero.front_image
        td= hero.back_image
        td= link_to 'Show', hero
        td= link_to 'Edit', edit_hero_path(hero)
        td= link_to 'Destroy', hero, method: :delete, data: {confirm: 'Are you sure?'}
br/
= link_to 'New Hero', new_hero_path




def anagrams(word,wordlist)
  words = wordlist.split(',')
  result = []
  word.split('').each do |char|
    words.each do |current_word| 
      result << current_word if word.include?(current_word)
    end
    word = word.chars.rotate.join  
  end  
  result
end
puts anagrams("horse","horse,shore,who,show,heros,gaefa,jggwegw,hhrrs")
puts 'end'

app/views/heros/new.html.slim
h1 New Hero
= render 'form', hero: @hero
= link_to 'Back', heros_path

app/views/heros/show.html.slim
p#notice= notice
p
  strong Name:
  = @hero.name
p
  strong Max fire:
  = @hero.max_fire
p
  strong Max earth:
  = @hero.max_earth
p
  strong Max water:
  = @hero.max_water
p
  strong Max wind:
  = @hero.max_wind
p
  strong Max atk:
  = @hero.max_atk
p
  strong Max lif:
  = @hero.max_lif
p
  strong Max def:
  = @hero.max_def
p
  strong Portarit pic:
  = @hero.portarit_pic
p
  strong Front image:
  = @hero.front_image
p
  strong Back image:
  = @hero.back_image
= link_to 'Edit', edit_hero_path(@hero)
| \
= link_to 'Back', heros_path