config/routes.rb
Rails.application.routes.draw do
  resources :move_sets
  resources :battle_logs
  resources :player_heros
  resources :heros
  devise_for :players
  devise_scope :player do
    root to: "devise/sessions#new"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/move_set.rb
class MoveSet < ApplicationRecord
end

app/controllers/move_sets_controller.rb
class MoveSetsController < ApplicationController
  before_action :set_move_set, only: [:show, :edit, :update, :destroy]

  # GET /move_sets
  # GET /move_sets.json
  def index
    @move_sets = MoveSet.all
  end

  # GET /move_sets/1
  # GET /move_sets/1.json
  def show
  end

  # GET /move_sets/new
  def new
    @move_set = MoveSet.new
  end

  # GET /move_sets/1/edit
  def edit
  end

  # POST /move_sets
  # POST /move_sets.json
  def create
    @move_set = MoveSet.new(move_set_params)

    respond_to do |format|
      if @move_set.save
        format.html { redirect_to @move_set, notice: 'Move set was successfully created.' }
        format.json { render :show, status: :created, location: @move_set }
      else
        format.html { render :new }
        format.json { render json: @move_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /move_sets/1
  # PATCH/PUT /move_sets/1.json
  def update
    respond_to do |format|
      if @move_set.update(move_set_params)
        format.html { redirect_to @move_set, notice: 'Move set was successfully updated.' }
        format.json { render :show, status: :ok, location: @move_set }
      else
        format.html { render :edit }
        format.json { render json: @move_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /move_sets/1
  # DELETE /move_sets/1.json
  def destroy
    @move_set.destroy
    respond_to do |format|
      format.html { redirect_to move_sets_url, notice: 'Move set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_move_set
      @move_set = MoveSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def move_set_params
      params.require(:move_set).permit(:name, :requirements, :power, :effects, :mana_effects, :image, :sfx, :vfx)
    end
end

app/helpers/move_sets_helper.rb
module MoveSetsHelper
end

app/views/move_sets/_form.html.erb
<%= form_with(model: move_set, local: true) do |form| %>
  <% if move_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(move_set.errors.count, "error") %> prohibited this move_set from being saved:</h2>

      <ul>
      <% move_set.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :move_set_name %>
  </div>

  <div class="field">
    <%= form.label :requirements %>
    <%= form.text_field :requirements, id: :move_set_requirements %>
  </div>

  <div class="field">
    <%= form.label :power %>
    <%= form.text_field :power, id: :move_set_power %>
  </div>

  <div class="field">
    <%= form.label :effects %>
    <%= form.text_field :effects, id: :move_set_effects %>
  </div>

  <div class="field">
    <%= form.label :mana_effects %>
    <%= form.text_field :mana_effects, id: :move_set_mana_effects %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :move_set_image %>
  </div>

  <div class="field">
    <%= form.label :sfx %>
    <%= form.text_field :sfx, id: :move_set_sfx %>
  </div>

  <div class="field">
    <%= form.label :vfx %>
    <%= form.text_field :vfx, id: :move_set_vfx %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/move_sets/edit.html.erb
<h1>Editing Move Set</h1>

<%= render 'form', move_set: @move_set %>

<%= link_to 'Show', @move_set %> |
<%= link_to 'Back', move_sets_path %>

app/views/move_sets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Move Sets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Requirements</th>
      <th>Power</th>
      <th>Effects</th>
      <th>Mana effects</th>
      <th>Image</th>
      <th>Sfx</th>
      <th>Vfx</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @move_sets.each do |move_set| %>
      <tr>
        <td><%= move_set.name %></td>
        <td><%= move_set.requirements %></td>
        <td><%= move_set.power %></td>
        <td><%= move_set.effects %></td>
        <td><%= move_set.mana_effects %></td>
        <td><%= move_set.image %></td>
        <td><%= move_set.sfx %></td>
        <td><%= move_set.vfx %></td>
        <td><%= link_to 'Show', move_set %></td>
        <td><%= link_to 'Edit', edit_move_set_path(move_set) %></td>
        <td><%= link_to 'Destroy', move_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Move Set', new_move_set_path %>

app/views/move_sets/new.html.erb
<h1>New Move Set</h1>

<%= render 'form', move_set: @move_set %>

<%= link_to 'Back', move_sets_path %>

app/views/move_sets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @move_set.name %>
</p>

<p>
  <strong>Requirements:</strong>
  <%= @move_set.requirements %>
</p>

<p>
  <strong>Power:</strong>
  <%= @move_set.power %>
</p>

<p>
  <strong>Effects:</strong>
  <%= @move_set.effects %>
</p>

<p>
  <strong>Mana effects:</strong>
  <%= @move_set.mana_effects %>
</p>

<p>
  <strong>Image:</strong>
  <%= @move_set.image %>
</p>

<p>
  <strong>Sfx:</strong>
  <%= @move_set.sfx %>
</p>

<p>
  <strong>Vfx:</strong>
  <%= @move_set.vfx %>
</p>

<%= link_to 'Edit', edit_move_set_path(@move_set) %> |
<%= link_to 'Back', move_sets_path %>