config/routes.rb
Rails.application.routes.draw do
  resources :move_sets
  resources :battle_logs
  resources :player_heros
  resources :heros
  devise_for :players
  devise_scope :player do
    root to: "devise/sessions#new"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/battle_log.rb
class BattleLog < ApplicationRecord
  belongs_to :battle
end

app/controllers/battle_logs_controller.rb
class BattleLogsController < ApplicationController
  before_action :set_battle_log, only: [:show, :edit, :update, :destroy]

  # GET /battle_logs
  # GET /battle_logs.json
  def index
    @battle_logs = BattleLog.all
  end

  # GET /battle_logs/1
  # GET /battle_logs/1.json
  def show
  end

  # GET /battle_logs/new
  def new
    @battle_log = BattleLog.new
  end

  # GET /battle_logs/1/edit
  def edit
  end

  # POST /battle_logs
  # POST /battle_logs.json
  def create
    @battle_log = BattleLog.new(battle_log_params)

    respond_to do |format|
      if @battle_log.save
        format.html { redirect_to @battle_log, notice: 'Battle log was successfully created.' }
        format.json { render :show, status: :created, location: @battle_log }
      else
        format.html { render :new }
        format.json { render json: @battle_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /battle_logs/1
  # PATCH/PUT /battle_logs/1.json
  def update
    respond_to do |format|
      if @battle_log.update(battle_log_params)
        format.html { redirect_to @battle_log, notice: 'Battle log was successfully updated.' }
        format.json { render :show, status: :ok, location: @battle_log }
      else
        format.html { render :edit }
        format.json { render json: @battle_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /battle_logs/1
  # DELETE /battle_logs/1.json
  def destroy
    @battle_log.destroy
    respond_to do |format|
      format.html { redirect_to battle_logs_url, notice: 'Battle log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_battle_log
      @battle_log = BattleLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def battle_log_params
      params.require(:battle_log).permit(:battle_id, :action, :player_hero_atk, :player_hero_def, :result)
    end
end

app/helpers/battle_logs_helper.rb
module BattleLogsHelper
end

app/views/battle_logs/_form.html.slim
= form_with(model: battle_log, local: true) do |form|
  - if battle_log.errors.any?
    #error_explanation
      h2
        = pluralize(battle_log.errors.count, "error")
        | prohibited this battle_log from being saved:
      ul
        - battle_log.errors.full_messages.each do |message|
          li= message
  .field
    = form.label :battle_id
    = form.text_field :battle_id, id: :battle_log_battle_id
  .field
    = form.label :action
    = form.text_field :action, id: :battle_log_action
  .field
    = form.label :player_hero_atk
    = form.text_field :player_hero_atk, id: :battle_log_player_hero_atk
  .field
    = form.label :player_hero_def
    = form.text_field :player_hero_def, id: :battle_log_player_hero_def
  .field
    = form.label :result
    = form.text_field :result, id: :battle_log_result
  .actions
    = form.submit

app/views/battle_logs/edit.html.slim
h1 Editing Battle Log
= render 'form', battle_log: @battle_log
= link_to 'Show', @battle_log
| \
= link_to 'Back', battle_logs_path

app/views/battle_logs/index.html.slim
p#notice= notice
h1 Battles
table
  thead
    tr
      th #
      th Challanger
      th Challanged
      th Hero Challenger
      th Hero Challanged
      th Max atk
      th Max lif
      th Max def
      th Portarit pic
      th Front image
      th Back image
      th colspan: "3" 
  tbody
    - @battles.each do |b|
      tr
        td= b.id
        td
            a 
                b.player_challenger
        td= hero.max_earth
        td= hero.max_water
        td= hero.max_wind
        td= hero.max_atk
        td= hero.max_lif
        td= hero.max_def
        td= hero.portarit_pic
        td= hero.front_image
        td= hero.back_image
        td= link_to 'Show', hero
        td= link_to 'Edit', edit_hero_path(hero)
        td= link_to 'Destroy', hero, method: :delete, data: {confirm: 'Are you sure?'}
br/
= link_to 'New Hero', new_hero_path

app/views/battle_logs/new.html.slim
h1 New Battle Log
= render 'form', battle_log: @battle_log
= link_to 'Back', battle_logs_path

app/views/battle_logs/show.html.slim
p#notice= notice
p
  strong Battle:
  = @battle_log.battle
p
  strong Action:
  = @battle_log.action
p
  strong Player hero atk:
  = @battle_log.player_hero_atk
p
  strong Player hero def:
  = @battle_log.player_hero_def
p
  strong Result:
  = @battle_log.result
= link_to 'Edit', edit_battle_log_path(@battle_log)
| \
= link_to 'Back', battle_logs_path