config/routes.rb
Rails.application.routes.draw do
  resources :move_sets
  resources :battle_logs
  resources :player_heros
  resources :heros
  devise_for :players
  devise_scope :player do
    root to: "devise/sessions#new"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/player_hero.rb
class PlayerHero < ApplicationRecord
  belongs_to :player
  belongs_to :hero

  def reset_stats
    self.atk = hero.max_atk
    self.def = hero.max_def
    self.life = hero.max_life
  end
end

app/controllers/player_heros_controller.rb
class PlayerHerosController < ApplicationController
  before_action :set_player_hero, only: [:show, :edit, :update, :destroy]

  # GET /player_heros
  # GET /player_heros.json
  def index
    @player_heros = PlayerHero.all
  end

  # GET /player_heros/1
  # GET /player_heros/1.json
  def show
  end

  # GET /player_heros/new
  def new
    @player_hero = PlayerHero.new
  end

  # GET /player_heros/1/edit
  def edit
  end

  # POST /player_heros
  # POST /player_heros.json
  def create
    @player_hero = PlayerHero.new(player_hero_params)

    respond_to do |format|
      if @player_hero.save
        format.html { redirect_to @player_hero, notice: 'Player hero was successfully created.' }
        format.json { render :show, status: :created, location: @player_hero }
      else
        format.html { render :new }
        format.json { render json: @player_hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /player_heros/1
  # PATCH/PUT /player_heros/1.json
  def update
    respond_to do |format|
      if @player_hero.update(player_hero_params)
        format.html { redirect_to @player_hero, notice: 'Player hero was successfully updated.' }
        format.json { render :show, status: :ok, location: @player_hero }
      else
        format.html { render :edit }
        format.json { render json: @player_hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_heros/1
  # DELETE /player_heros/1.json
  def destroy
    @player_hero.destroy
    respond_to do |format|
      format.html { redirect_to player_heros_url, notice: 'Player hero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player_hero
      @player_hero = PlayerHero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_hero_params
      params.require(:player_hero).permit(:player_id, :bat_fire, :bat_earth, :bat_water, :bat_wind, :atk, :life, :def)
    end
end

app/helpers/player_heros_helper.rb
module PlayerHerosHelper
end

app/views/player_heros/_form.html.slim
= form_with(model: player_hero, local: true) do |form|
  - if player_hero.errors.any?
    #error_explanation
      h2
        = pluralize(player_hero.errors.count, "error")
        | prohibited this player_hero from being saved:
      ul
        - player_hero.errors.full_messages.each do |message|
          li= message
  .field
    = form.label :player_id
    = form.text_field :player_id, id: :player_hero_player_id
  .field
    = form.label :bat_fire
    = form.number_field :bat_fire, id: :player_hero_bat_fire
  .field
    = form.label :bat_earth
    = form.number_field :bat_earth, id: :player_hero_bat_earth
  .field
    = form.label :bat_water
    = form.text_field :bat_water, id: :player_hero_bat_water
  .field
    = form.label :bat_wind
    = form.number_field :bat_wind, id: :player_hero_bat_wind
  .field
    = form.label :atk
    = form.number_field :atk, id: :player_hero_atk
  .field
    = form.label :life
    = form.number_field :life, id: :player_hero_life
  .field
    = form.label :def
    = form.number_field :def, id: :player_hero_def
  .actions
    = form.submit

app/views/player_heros/edit.html.slim
h1 Editing Player Hero
= render 'form', player_hero: @player_hero
= link_to 'Show', @player_hero
| \
= link_to 'Back', player_heros_path

app/views/player_heros/index.html.slim
p#notice= notice
h1 Player Heros
table
  thead
    tr
      th Player
      th Bat fire
      th Bat earth
      th Bat water
      th Bat wind
      th Atk
      th Life
      th Def
      th colspan: "3" 
  tbody
    - @player_heros.each do |player_hero|
      tr
        td= player_hero.player
        td= player_hero.bat_fire
        td= player_hero.bat_earth
        td= player_hero.bat_water
        td= player_hero.bat_wind
        td= player_hero.atk
        td= player_hero.life
        td= player_hero.def
        td= link_to 'Show', player_hero
        td= link_to 'Edit', edit_player_hero_path(player_hero)
        td= link_to 'Destroy', player_hero, method: :delete, data:   confirm: 'Are you sure?'  
br/
= link_to 'New Player Hero', new_player_hero_path

app/views/player_heros/new.html.slim
h1 New Player Hero
= render 'form', player_hero: @player_hero
= link_to 'Back', player_heros_path

app/views/player_heros/show.html.slim
p#notice= notice
p
  strong Player:
  = @player_hero.player
p
  strong Bat fire:
  = @player_hero.bat_fire
p
  strong Bat earth:
  = @player_hero.bat_earth
p
  strong Bat water:
  = @player_hero.bat_water
p
  strong Bat wind:
  = @player_hero.bat_wind
p
  strong Atk:
  = @player_hero.atk
p
  strong Life:
  = @player_hero.life
p
  strong Def:
  = @player_hero.def
= link_to 'Edit', edit_player_hero_path(@player_hero)
| \
= link_to 'Back', player_heros_path